### ISSUE TITLE
Add font awesome to be used on channels

### ISSUE THREAD

**Issue by rodrigojuarez** [Coding-Coach/mobile#14]

**Comment by Depechie** [comment]
Hey @rodrigojuarez could you explain a bit more the different classes available in https://github.com/Coding-Coach/mobile/blob/master/CodingCoach/CodingCoach/CustomControls/FontAwesomeIcon.cs ?

You could switch out type faces by using styles... even with triggers if needed ( http://depblog.weblogs.us/2018/12/06/xamarin-forms-switch-custom-font-on-style-trigger/ ) that way there would only be need of 1 control.

I think the ChannelView control could be using Label control itself with only a styles reference to get FontAwesome working.

**Comment by rodrigojuarez** [comment]
Sounds good @Depechie, I will check it, thanks!
