### ISSUE TITLE
Secrets file

### ISSUE THREAD

**Issue by Depechie** [Coding-Coach/mobile#18]
There is no secrest.json file in the solution.
So we can no longer build locally...

How do we work around this @rodrigojuarez ?

**Comment by rodrigojuarez** [comment]
@Depechie copy and rename the file secrets.json.template, I will update the readme file to include that info.

**Comment by Depechie** [comment]
Can you check in a version that has the right name. That way we don’t need to rename.

You can set git untrack to not include the local one with the secrets in it.

http://codeclimber.net.nz/archive/2016/12/19/ignoring-files-on-git-but-just-for-a-while-with-assume-unchanged/

**Comment by rodrigojuarez** [comment]
Can you do a PR with that?

**Comment by Depechie** [comment]
Sure!
But remember before you pull in that PR you still need to do that git command : git update-index --assume-unchanged <file>
Otherwise you will loose the one with the actual secrets in it.
Best to copy it somewhere else on disk and see what happens after the pull.

**Comment by rodrigojuarez** [comment]
Sounds good, thanks!
