### ISSUE TITLE
[Question] Why not a PWA?

### ISSUE THREAD

**Issue by SergejDK** [Coding-Coach/mobile#22]
Firstly I like the idea of having a mobile app for coding-coach! And Xamarin is a great tool to work with!

But why not implementing as a PWA? With this it could be possible to reuse nearly all content from the website? 
Or will it be like a Mobile App for the app store and still having a PWA ?

Just curious about it...

**Comment by rodrigojuarez** [comment]
This app is for the app stores, my idea is also to use it as a playground for any mentee that wants to work with Xamarin. Probably the PWA is currently under development, you should ask in the front-end channel in slack.

**Comment by rodrigojuarez** [comment]
@SergejDK also you can join the Xamarin channel in slack if you want to participate in the development.
