### ISSUE TITLE
Need of a Mobile Application?

### ISSUE THREAD

**Issue by calvinnor** [Coding-Coach/mobile#27]
Hey, I'm interested in building a Flutter application for CodingCoach.
Having a look at Swagger, I can use staging APIs without authentication. I also can't see a Login / Signup API that'll get me the User's Authorization token. Can you guide me?

This is an effort to learn the framework. I'm already well versed with native Android applications ;)

**Comment by rodrigojuarez** [comment]
Sorry for the long time, you should ask in https://github.com/Coding-Coach/find-a-mentor-api
Anyway, the API it's using Auth0 for auth related functionality
